// Labels:
// WLM - With letter modification
// SM - May introduce standalone meaning if the prefix is added

const prefixes = [
  // 'alas-', //SM
  // 'ala-', //SM

  // 'de-',
  // 'des-',
  // 'di-',
  // 'ekstra-',
  // 'elektro',
  /^gangga/,
  /^gaga/,
  /^ga/,

  // 'hin', //WLM
  // 'him', //WLM
  // 'hi',

  /^ikapakapagpaka/,
  /^ikapakapagpa/,
  /^ikapakapang/,
  /^ikapakapag(?![aeiou])/,
  /^ikapakapam/,
  /^ikapakapan/,
  /^ikapagpaka/,
  /^ikapakipan/,
  /^ikapakipag(?![aeiou])/,
  /^ikapakipam/,
  /^ikapakipa/,
  /^ipakipag(?![aeiou])/,
  /^ipagkang/,
  /^ikapagpa/,
  /^ikapaka/,
  /^ikapaki/,
  /^ikapang/,
  /^ipakipa/,
  /^ikapag(?![aeiou])/,
  /^ikapam/,
  /^ikapan/,
  /^ipagka/,
  /^ipagpa/,
  /^ipaka/,
  /^ipaki/,
  /^ikapa/,
  /^ipang/,
  /^ikang/,
  /^ipag(?![aeiou])/,
  /^ikam/,
  /^ikan/,
  /^isa/,
  /^ipa/,

  /^kasing/,
  // 'kontra',
  /^kamaka/,
  /^kanda/,
  /^kasim/,
  /^kasin/,
  /^kamag/,
  /^kaka/,
  /^ka/,

  // 'labing', //Forms new meaning

  /^mangagsipagpaka/,
  /^mangagsipag(?![aeiou])/,
  /^mangagpaka/,
  /^magsipagpa/,
  /^makapagpa/,
  /^mangagsi/,
  /^mangagpa/,
  /^magsipag(?![aeiou])/,
  /^mangagka/,
  /^magkang/,
  /^magpaka/,
  /^magpati/,
  /^makapag(?![aeiou])/,
  /^mapapag(?![aeiou])/,
  /^mapang/,
  /^mapasa/,
  /^mapapa/,
  /^mangag/,
  /^manga/,
  // 'mikro',
  /^magka/,
  /^magpa/,
  /^magsa/,
  /^mapag(?![aeiou])/,
  /^mapam/,
  /^mapan/,
  // 'meta',
  /^mapa/,
  /^mang/,
  // 'mini',
  /^maka/,
  /^maki/,
  // 'mala',
  // 'mal',
  /^mam/,
  /^man/,
  // 'may',
  /^mag(?![aeiou])/,
  /^ma/,

  /^nangagsipagpaka/,
  /^nangagsipagpa/,
  /^nagsipagpaka/,
  /^nakapagpaka/,
  /^nangagsipag(?![aeiou])/,
  /^nangagpaka/,
  /^nangagkaka/,
  /^nagsipagpa/,
  /^nakapagpa/,
  /^nagsipag(?![aeiou])/,
  /^nangagpa/,
  /^nangagka/,
  /^nangagsi/,
  /^nakapag(?![aeiou])/,
  /^nakipag(?![aeiou])/,
  /^napapag(?![aeiou])/,
  /^nagpaka/,
  /^nagpati/,
  /^nangag/,
  /^napaka/,
  /^napasa/,
  /^nanga/,
  /^nagka/,
  /^nagpa/,
  /^nagsa/,
  /^nagsi/,
  /^napag(?![aeiou])/,
  /^naka/,
  /^naki/,
  /^nang/,
  /^napa/,
  /^nag/,
  /^na/,

  /^pagpapati/,
  /^pagpapaka/,
  /^pagpapa/,
  /^pagsasa/,
  /^pasasa/,
  /^pakiki/,
  /^pinaka/,
  /^pinag/,
  /^pinag/,
  /^papag(?![aeiou])/,
  /^pampa/,
  /^panag/,
  /^pagka/,
  /^paka/,
  /^paki/,
  /^pala/,
  /^pang/,
  /^pani/,
  /^papa/,
  /^para/,
  /^pasa/,
  /^pati/,
  /^pina/,
  /^pag(?![aeiou])/,
  /^pam/,
  /^pan/,
  /^pa/,

  // 'xeno',

  // 'radyo',

  // /^re/,

  /^sang/,
  /^sing/,
  // /^sam/,
  // /^san/,
  /^sin/,
  // /^sa/,

  /^tagapag(?![aeiou])/,
  /^taga/,
  /^tiga/,
  /^tag/,
  /^tig/,
  // 'uni',
  /^um/
];

const suffixes = ['han', 'hin', 'an', 'in'];

const infixes = ['in', 'um'];

module.exports = { prefixes, suffixes, infixes };
